### ISSUE TITLE
bin/ld.exe: cannot find -ltensorflow_framework when trying to run compile_op.sh

### ISSUE THREAD

**Issue by ChandlerTayek** [azuki-miho/RFCR#2]
Hello, I'm currently trying to follow the `KPConv_deform_Semantic3D/INSTALL.md` instructions using Windows 10, python 3.9, CUDA 11.3.1, and CUDNN 8.2.1.

When trying to `Compile the customized Tensorflow operators located in tf_custom_ops` I'm getting the error
`c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32
bin/ld.exe: cannot find 
-ltensorflow_framework
collect2.exe: error: ld returned 1 exit status
`

I noticed that `-ltensorflow_framework` is a flag set in the command to run the `.cpp` file. Any help would be appreciated.

**Comment by azuki-miho** [comment]
Thanks for your question. We have just tested our code on Ubuntu 18.04, maybe you can try it with a Ubuntu Server.

**Comment by ChandlerTayek** [comment]
I'm gonna try again with an Ubutnu VM but thought this was just worth mentioning. Thanks for the response @azuki-miho
